### ISSUE TITLE
Update composer.json to limit installs from using Composer > 2.6.x

### ISSUE THREAD

**Issue by kreynen** [pantheon-systems/upstream-management#4]
I'm going to start using a more GitLab approach to issues about issues with an open source component discussed as part of a paid service and reference the ZenDesk ticket number this discussion took place in knowing that only the people working for the custom and Pantheon can see those details. When we have issues with a GitLab SaaS instance, it's GitLab support that opens or adds to the issues each time someone with a paid support contract reports the same problem like what you see in https://gitlab.com/gitlab-org/gitlab/-/issues/390932

In this case in issue #880884, Pantheon support confirmed that this package is not compatible with Composer 2.7.x...

> our engineering team has already started their work on the bug report I have raised but I am afraid I cannot share any ETA when will the compatibility issue with Composer 2.7.* be resolved. Since there's a workaround to use the lower versions of Composer for now

Rather than only discuss this in private support channels, the standard process should have been to open an issue to update https://github.com/pantheon-systems/upstream-management/blob/main/composer.json#L8

**Comment by kreynen** [comment]
Suggested PR to avoid other users having this same issue https://github.com/pantheon-systems/upstream-management/pull/5

**Comment by kporras07** [comment]
Thanks!

Fixed in #6
